steps:
- name: 'gcr.io/$PROJECT_ID/scala-sbt'
  args: ['docker:publishLocal']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'podcasts-rss:0.1.0-SNAPSHOT', 'eu.gcr.io/$PROJECT_ID/podcasts-rss:0.1.0-SNAPSHOT']
images:
- 'eu.gcr.io/$PROJECT_ID/podcasts-rss:0.1.0-SNAPSHOT'
